<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Engzly.Notification-e6ff047c-3ce8-4892-83ab-b31610c8243b</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FirebaseAdmin" Version="3.4.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Messaging\Fitlers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Engzly.Shared\Engzly.Shared.csproj" />
    </ItemGroup>
</Project>
